### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by mastercho** [JBou/CloudProxySharp#2]
Hi

Just wonder if you can add Proxy support which is merged here https://github.com/NoahCardoza/CloudProxy/pull/44

**Comment by JBou** [comment]
Should be fixed by https://github.com/JBou/CloudProxySharp/commit/829d3f19d293aaf9989250e914f996012809ccc7
I will release v1.0.2 on nuget now. It should be working, otherwise please reopen the issue.
More information on how to use the proxy feature can be found [here](https://www.chromium.org/developers/design-documents/network-settings).
